### ISSUE TITLE
How to extract X and Theta

### ISSUE THREAD

**Issue by dlunga** [cuMF/cumf_sgd#1]
How and where do I extract X and Theta after convergence? Are these being written to a file on the host device?

**Comment by xlxie** [comment]
Hi,

Of course, X and Theta are written to the disk, which we call it "model file".

By default, the model file locates in the same directory with the input train file and the file name is "$(train_file_name).model". 

As for the format of the file, we use the same format with LIBMF(https://github.com/cjlin1/libmf), the only difference is we use binary format while they use txt format. You can refer save_model() in file main.cpp for the details of the model file format.

Best regards,
