### ISSUE TITLE
The netflix dataset is not available.

### ISSUE THREAD

**Issue by Zialus** [cuMF/cumf_sgd#2]
Are there any alternative links?

**Comment by wei-tan** [comment]
We have it in ALS data format. Please see the "Input Data" Section at 
https://github.com/cuMF/cumf_als

**Comment by Zialus** [comment]
Yes, but I can't run the prepare script on these files.

```
-rw-r--r-- 1  5633580 May 11  2016 R_test_coo.col.bin
-rw-r--r-- 1  5633580 May 11  2016 R_test_coo.data.bin
-rw-r--r-- 1  5633580 May 11  2016 R_test_coo.row.bin
-rw-r--r-- 1  396288448 May 11  2016 R_train_coo.row.bin
-rw-r--r-- 1  396288448 May 11  2016 R_train_csc.data.bin
-rw-r--r-- 1  396288448 May 11  2016 R_train_csc.indices.bin
-rw-r--r-- 1  1920760 May 11  2016 R_train_csc.indptr.bin
-rw-r--r-- 1  396288448 May 11  2016 R_train_csr.data.bin
-rw-r--r-- 1  396288448 May 11  2016 R_train_csr.indices.bin
-rw-r--r-- 1  71084 May 11  2016 R_train_csr.indptr.bin
```

**Comment by xlxie** [comment]
Hi Raul，the data fornat is different，I am uploading cumf_sgd to Google drive，I will let you know when I finish it.
发自我的 iPhone

**Comment by xlxie** [comment]
Hi all, please find the netflix data set on the following link. 

Put all files in ./data/netflix and run ./data/netflix/run.sh 

https://drive.google.com/drive/folders/1ZxG4hVWqNGnlvPwx0T7lDwDq816GLXv-
