### ISSUE TITLE
Write conflicts in the update procedure.

### ISSUE THREAD

**Issue by xysmlx** [cuMF/cumf_sgd#3]
Hi, I think there is a bug in the 89-99 lines of cumf_sgd/singleGPU/sgd_k128_kernel_hogwild_warp32.h:

```
//update
//only works for k=blockDim.x=128
p[base_p + lane_id +  0] = __float2half(tmp_p1 + tmp_lrate*(ruv*tmp_q1 - lambda_p*tmp_p1));
q[base_q + lane_id +  0] = __float2half(tmp_q1 + tmp_lrate*(ruv*tmp_p1 - lambda_q*tmp_q1));

p[base_p + lane_id + 32] = __float2half(tmp_p2 + tmp_lrate*(ruv*tmp_q2 - lambda_p*tmp_p2));
q[base_q + lane_id + 32] = __float2half(tmp_q2 + tmp_lrate*(ruv*tmp_p2 - lambda_q*tmp_q2));

p[base_p + lane_id + 64] = __float2half(tmp_p3 + tmp_lrate*(ruv*tmp_q3 - lambda_p*tmp_p3));
q[base_q + lane_id + 64] = __float2half(tmp_q3 + tmp_lrate*(ruv*tmp_p3 - lambda_q*tmp_q3));

p[base_p + lane_id + 96] = __float2half(tmp_p4 + tmp_lrate*(ruv*tmp_q4 - lambda_p*tmp_p4));
q[base_q + lane_id + 96] = __float2half(tmp_q4 + tmp_lrate*(ruv*tmp_p4 - lambda_q*tmp_q4));
```

Multiple workers(blocks) or warps may update the same base_p or base_q so that there will be write conflicts. This procedure should use atomic operations.

**Comment by wei-tan** [comment]
It is meant to be in that way. 
You are correct that conflicting updates CAN HAPPEN, but they would be rare given the sparseness of the data. 
Using atomic operations will guarantee 100% correctness but impact the speed a lot.
This is the idea of hogwild. See this paper:
https://people.eecs.berkeley.edu/~brecht/papers/hogwildTR.pdf

**Comment by xlxie** [comment]
Hi Lingxiao,
          
Wei answered the question well. Your are right, cumf_sgd does not avoid simultaneous update on the same p row or q column. But it's not a bug, it's a feature. If we run 40 threads on a processor, using atomic functions is ok. If we run 40000 threads, it's not that way. The following paper evaluated some lock-based parallelization solutions:

Rashid Kaleem, Sreepathi Pai, and Keshav Pingali. 2015. Stochastic gradient descent on GPUs. In Proceedings of the 8th Workshop on General Purpose Processing using GPUs (GPGPU-8)

Our idea is to trade subtle accuracy loss for  training speed. After examining different solutions, we observe that our solution achieves the fastest convergence speed.

**Comment by xysmlx** [comment]
Hi Wei and Xiaolong,

Thank you for your answering. I have understood this design. This idea is good.
