### ISSUE TITLE
netflix_mm/netflix_mme file

### ISSUE THREAD

**Issue by nathreed** [cuMF/cumf_sgd#4]
Hi,

I'm doing some unrelated research, resurrecting a project from a couple years ago. It relies on the netflix_mm and netflix_mme files, which seem to have completely disappeared from the Internet. Your README does mention these files as being in your google drive link, but I can't seem to find them (you have netflix_train and netflix_test, but these appear to be in a different format). 

Do you, by any chance, have the netflix_mm and netflix_mme files, and would it be at all possible for you to (temporarily) upload them somewhere where I could download them? It would be much appreciated.

Thanks in advance!

**Comment by xlxie** [comment]
Hi,

I just wrote a script to transform the netflix dataset into the original formats, please checkout [netflix](https://drive.google.com/drive/folders/1ZxG4hVWqNGnlvPwx0T7lDwDq816GLXv-?usp=sharing). （netflix_mm & netflix_mme）

In this format, each line contains three comma-separated numbers, user id, item id and the rating. I am not sure if it's exactly the same with original format. But I think it's easy to transform to any format you want. If you need any further help, please let me know.

I would be very happy it this does help.

Xiaolonglong

**Comment by nathreed** [comment]
Thank you very much! This is quite helpful. I appreciate your response.
